### ISSUE TITLE
Create an interface that contains the Conflict resolution

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#104]
We can have an interface in our library that the users can implement in their app and provide a custom conflict resolution implementation.

For instance, we can have an interface named `ConflictResolutionImpl` which contains an abstract method called 
```
public Mutation resolveConflict(serverState, clientState);
```

Now the users can create their own implementation of this interface and pass it to our `OffixConflictInterceptor` in its constructor parameters.

So the flow is : 
1. Users give us an implementation of conflictResolutionImpl while adding the Interceptor.
2. We detect the conflicts and call the `resolveConflict` method of this interface with `serverData` and `clientData`.
3. The users handle the conflict on their end and make the network call.

@wtrocki @Lavanyagaur22 let me know how this flow looks? Using this, we can effectively remove the `onConflict` method from our code which in turn reduces the code repetition that users have to perform while they override this `onConflict` method.

So essentially, our users can have a single isolated file where they handle the conflicts.

**Comment by wtrocki** [comment]
Same as in JS SDK we can also pass typename or operation name to know what object we are dealing with

**Comment by harshithdwivedi** [comment]
Makes sense.

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Can we also store mutation with us as of now in the `ConflictResolutionImpl` which will look like this: 
```kotlin
interface ConflictResolutionImpl {
    fun resolveConflict(
        serverState: Map<String, Any>,
        clientState: Map<String, Any>,
        operationType: String,
        conflictedMutation:Mutation<Operation.Data, Any, Operation.Variables>
    )
}
```
Because here we would have to follow an approach as we did in offline support, making calls using reflection. Because the user would be resolving conflicts in the class which extends this interface, so he can not make a mutation object again as other parameters would not be known to him. ( also mutation is made using builder method on the class name so by reflection we can't make it again as we can't get access to the builder)

We can make a variable called `resolvedValuesMap` which stores the mutation variables after resolving conflicts, something like this:

```kotlin
class UserConflictResolutionhandler : ConflictResolutionImpl {

    override fun resolveConflict(
        serverState: Map<String, Any>,
        clientState: Map<String, Any>,
        operationType: String,
        conflictedMutation: Mutation<Operation.Data, Any, Operation.Variables>
    ) {
        val serverMap = serverState
        lateinit var resolvedValuesMap: MutableMap<String, Any>

        val containsVersion = serverMap.containsKey("version")

        if (containsVersion) {
            var versionAfterConflict = serverMap.get("version") as Int + 1

            clientState.keys.forEach { key ->
                if (key == "version") {
                    resolvedValuesMap.put(key, versionAfterConflict)
                }
                clientState.get(key)?.let { resolvedValuesMap.put(key, it) }
            }
        }
        conflictedMutation.variables().valueMap(resolvedValuesMap)
    }
}
``` 
And then after we resolve the conflict in conflictedMutation, we can make a server call here again.  

WDYT? Any other approach you can help me out with?

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 Users can have a switch() - case statement inside their interface implementation which checks for the type of operation which caused the conflict and handle it accordingly.

So for example if a create operation caused conflict, I would handle it differently as compared to an update operation.

We don't need to send the conflicted Mutation object back to them; they can simply create different Mutation Objects based on the type of operation that caused the conflict.

I hope that makes sense?

**Comment by wtrocki** [comment]
I agree with @harshithdwivedi
