### ISSUE TITLE
Apollo cache watcher not working properly.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#141]
### Description

**Bug**: After adding subscriptions in the sample, the cache is getting updated on every request. We are getting fresh and correct data in the cache, but on refreshing app when we try to fetch data from cache ( apollo watcher attached to the cache ), we are not getting the data from the cache.

**Comment by wtrocki** [comment]
Subscriptions need to provide cache update method that will update cache. 
Generall rule is to not use subscriptions to feed data directly to the UI, but put it into the cache.

Then we have single source of the truth that comes from cache - it can be query or subscription.
However this issue is probably because we use cache first strategy that will not execute query if the query is cached. If we want to get fresh data we should use network-only query first.

**Comment by wtrocki** [comment]
This is problem with sample app implementation rather than library itself. 
We need to provide helpers or at least document how to work with offline cases. 
I believe that we are missing here documentation that will be addressed in separate issue
